### ISSUE TITLE
获取到的海报从大尺寸变成了小尺寸的

### ISSUE THREAD

**Issue by Pezeo** [xiadong1994/bangumi_yearly_report#14]
小：https://lain.bgm.tv/pic/cover/c/e1/5a/95225_nuqNt.jpg
大：https://lain.bgm.tv/pic/cover/l/e1/5a/95225_nuqNt.jpg

**Comment by Shell32-Natsu** [comment]
是的，默认的封面从`s`变成了`c`了，我等下改一下。

**Comment by Shell32-Natsu** [comment]
Fixed
